version: '3.4'
services:
    plexripper:
        container_name: PlexRipper
        image: plexripper/plexripper
        build:
            context: .
            dockerfile: src/WebAPI/Dockerfile
        restart: always
        ports:
            # Web UI
            - '3000:3000'
            # Web API
            - '5000:5000'
