version: '3.4'
services:
    plexripper:
        container_name: PlexRipper
        image: plexripper/plexripper
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            # Web UI & Web API
            - '7000:7000'
        restart: unless-stopped