version: '3.4'
services:
    plexripper:
        container_name: PlexRipper
        image: plexripper/plexripper
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=http://+:7000
        build:
            context: .
            dockerfile: ./Dockerfile
        # restart: always
        ports:
            # Web UI & Web API
            - '7000:7000'
        restart: unless-stopped