version: '3.4'
services:
    plexripper:
        container_name: PlexRipper
        image: plexripper/plexripper
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=http://+:5000
        build:
            context: .
            dockerfile: ./Dockerfile
        # restart: always
        ports:
            # Web UI & Web API
            - '5000:5000'
